### ISSUE TITLE
Issues with ownCloud 8?

### ISSUE THREAD

**Issue by mbrandis** [georgehrke/cl-calendarimport#7]
Hi!

I would like to use your script for automatic import of an ics file, but I do get the following error:

PHP Fatal error:  Call to a member function isEmpty() on null in owncloud/apps/calendar/lib/app.php on line 146

Is that a problem with the script or the ics file? 

I am using ownCloud 8.0.5.

**Comment by georgehrke** [comment]
please file a bug report in the calendar app and __use the issue template__

**Comment by mbrandis** [comment]
Thank you for the information!
